#! /bin/sh
# Starts and stops Mosca
# /etc/init.d/mosca
### BEGIN INIT INFO
# Provides:     mosca
# Required-Start:       $syslog
# Required-Stop:        $syslog
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Mosca initialisation
### END INIT INFO
# This runs as the user called pi - please change as you require
USER=pi
 
# The log is written to here - please make sure your user has write permissions.
LOG=/var/log/mosca.log

#Load up mosca when called
case "$1" in
 
start)
    if pgrep ^mosca$ > /dev/null
    then
        echo "Mosca already running."
    else
        echo "Starting Mosca.."
        touch $LOG
        chown $USER:$USER $LOG
        echo "" >> $LOG
        echo "Mosca service start: "$(date) >> $LOG

        su -l $USER -c "mosca -v --http-port 3000 --http-bundle --http-static ./ | bunyan >> $LOG &"
        echo "Logging to "$LOG
    fi
;;
 
stop)
    echo "Stopping Mosca.."

    pkill -SIGINT ^mosca$
    sleep 2
    echo "" >> $LOG
    echo "Node-RED service stop: "$(date) >> $LOG
;;
 
restart)
        echo "Restarting Mosca.."
        $0 stop
        sleep 2
        $0 start
        echo "Restarted."
;;
*)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac
